[ 1단계 - 체스판 초기화 ] 이유빈 미션 제출합니다.
poi1649/java-chess pull request #1
Opened 2024-03-27 09:14 UTC by leeshin20

2024-03-28 10:38 UTC, poi1649 requested changes
안녕하세요! 
일주일 고생 많으셨습니다. 
일단 요구사항에 대한 리뷰만 빠르게 남겨보았으니 수정 후, 다시 요청주세요! 👍

2024-03-28 10:38 UTC, poi1649 commented on src/main/java/chess/Position.java
> +        this.column = column;
커밋 기록으로 봤을 때, 두 가지 요구사항을 모두 지켜주지 않은 것 같아요
`모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. `
`모든 원시 값과 문자열을 포장한다`

2024-03-28 10:38 UTC, poi1649 commented on README.md
> +2. 흑, 백 기물 생성
계속해서 문서 업데이트 해주는 거 너무 좋네요 👍 문서도 코드처럼 계속해서 수정해주면 어떤 이점이 있을까요?

2024-03-28 10:38 UTC, poi1649 commented on src/main/java/chess/Piece.java
> +        PAWN("P");
K, Q, B 와 같이 출력을 위해 필요한 것들이 비즈니스 기능을 담당하는 클래스에 침투해있어도 괜찮을까요?

2024-03-28 10:38 UTC, poi1649 commented on src/main/java/chess/Board.java
> +        board.put(new Position('H',7), new Piece(Piece.Type.PAWN, Piece.Team.BLACK));
ㅋㅋㅋㅋㅋㅋ... 이게 최선일까요.. 매직넘버라도 수정해볼 수 없을까요?

2024-03-28 10:38 UTC, poi1649 commented on src/main/java/chess/Position.java
> +    }
equals와 hashcode를 함께 정의해야하는 이유는 무엇일까요?

2024-03-28 10:38 UTC, poi1649 commented on src/main/java/chess/ui/OutputView.java
> +        for (int row = 8; row >= 1; row--) {
여기도 매직넘버가 있네요 ㅠㅠ
매직넘버가 있으면 어떤 점에서 안좋을까요?

2024-03-28 10:38 UTC, poi1649 commented on src/main/java/chess/Board.java
> +        }
setter라고 생각해서 getter 밑에 위치시키신걸까요?
setter의 정의는 뭘까요

2024-03-28 10:38 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +        if (InputView.inputCommand().equals("start")) {
상수로 분리해서 관리할 순 없을까요?

2024-03-28 10:38 UTC, poi1649 commented on src/main/java/chess/Piece.java
> +    public enum Team {
다른 클래스로 분리해주지 않고 내부에 넣으신 이유가 있을까요?

2024-03-28 10:38 UTC, poi1649 commented on src/test/java/chess/PositionTest.java
> +    }
1. 테스트 이름은 왜 set 일까요?
2. 과연 필요한 테스트일까요? 포지션이 8을 넘는 양수이거나 음수가 들어오는 경우에 대한 방어 로직 같은 것들에 대해 테스트가 필요하지는 않을까요?
3. 테스트를 위해 프로덕션 코드에 불필요한 getter를 꼭 만들어야할까요?

2024-03-28 10:38 UTC, poi1649 commented on src/main/java/chess/ui/OutputView.java
> +        for (char col = 'A'; col <= 'H'; col++) {
`모든 원시 값과 문자열을 포장한다` 
놓친 요구사항이 있는 것 같아요!

2024-04-02 08:44 UTC, leeshin20 commented on README.md
> +2. 흑, 백 기물 생성
처음부터 완벽하게 정리하여 문서화 하는 것은 어렵기 때문에 구현을 하면서 문서를 작성할 때는 미처 생각하지 못 했던 부분이나, 생각했던 대로 구현이 되지 않는 등...
실제 코드를 작성하다 보면 변동이 생길 가능성이 항상 있습니다. 그래서 초기 문서를 그대로 두는 것 보다, 계속해서 바뀐 점을 문서에 반영해 주는 것이 좀 더 꼼꼼하게 기능을 구현하는데 도움이 될 것 이라고 생각합니다.

2024-04-02 08:50 UTC, leeshin20 commented on src/main/java/chess/Piece.java
> +        PAWN("P");
말씀하신대로 기물의 앞 글자 이니셜은 출력을 할 때만 사용이 되는 부분이기 때문에,
Output을 담당하는 클래스로 분리하는 것이 맞다고 생각됩니다.

해당 부분을 수정 하였지만 리뷰 내용을 잘못 이해해서, Piece 클래스에 출력에 관여되는 코드가 아직 남아있는 형태가 되었습니다.
해당 내용 다시 수정하도록 하겠습니다!

2024-04-02 08:54 UTC, leeshin20 commented on src/main/java/chess/Board.java
> +        board.put(new Position('H',7), new Piece(Piece.Type.PAWN, Piece.Team.BLACK));
```
 private void initializeBlackPiece() {
        board.put(new Position(1, 8), new Piece(Type.ROOK, Team.BLACK));
        board.put(new Position(2, 8), new Piece(Type.KNIGHT, Team.BLACK));
        board.put(new Position(3, 8), new Piece(Type.BISHOP, Team.BLACK));
        board.put(new Position(4, 8), new Piece(Type.KING, Team.BLACK));
        board.put(new Position(5, 8), new Piece(Type.QUEEN, Team.BLACK));
        board.put(new Position(6, 8), new Piece(Type.BISHOP, Team.BLACK));
        board.put(new Position(7, 8), new Piece(Type.KNIGHT, Team.BLACK));
        board.put(new Position(8, 8), new Piece(Type.ROOK, Team.BLACK));
        for (int file = Position.FIRST_FILE; file <= Position.LAST_FILE; file++) {
            board.put(new Position(file, 7), new Piece(Type.PAWN, Team.BLACK));
        }
    }
```
더 짧고 깔끔하게 표현할 수 있는 방법을 찾아보겠습니다!

2024-04-02 08:56 UTC, leeshin20 commented on src/main/java/chess/ui/OutputView.java
> +        for (int row = 8; row >= 1; row--) {
매직넘버를 사용하게 된다면, 
다른 사람이 해당 매직넘버를 봤을 때, 가독성이 떨어져 정확히 어떤 수를 의미하는지 한 눈에 파악하기 힘들어지는 문제가 생기며
해당 매직넘버를 여러 곳에 사용했다면 값을 수정할 때, 여러 번 수정해야되는 유지보수의 어려움이 생깁니다.
상수로 대체하는 것이 바람직한 것 같습니다.

2024-04-02 09:03 UTC, leeshin20 commented on src/main/java/chess/Board.java
> +        }
setter는 외부의 클래스가 특정 필드의 값에 접근하여 값을 설정하거나 수정하는 기능을 합니다.

setBlackPiece메서드의 경우는 외부가 아닌 클래스 내부에서 호출이 되며, 보드 상태의 초기화를 목적으로 하고 있기 때문에 setter와는 거리가 멀다고 생각이 됩니다.

해당 메서드의 위치는 그냥 getPiece메서드를 작성한 뒤에 setBlackPiece메서드를 작성하여 밑에 위치가 된 것 같습니다...

2024-04-02 09:04 UTC, leeshin20 commented on src/main/java/chess/ChessGameManager.java
> +        if (InputView.inputCommand().equals("start")) {
현재 사용자가 입력할 수 있는 두 가지 명령어를
`START_COMMAND`, `END_COMMAND`로 각각 상수로 분리하여 적용했습니다!

2024-04-02 09:07 UTC, leeshin20 commented on src/main/java/chess/Piece.java
> +    public enum Team {
기물이 팀 정보와 기물타입에 대한 정보를 가지고 있어야 된다는 점 때문에, `Piece`, `Team`, `Type`을 각각 분리할 생각을 하지 못 하고 하나의 클래스에 함께 코드를 작성한 것 같습니다.

`Team`과 `Type`을 별도의 파일로 분리하였습니다!

2024-04-02 09:09 UTC, leeshin20 commented on src/main/java/chess/ui/OutputView.java
> +        for (char col = 'A'; col <= 'H'; col++) {
수정했습니다!

원시 값을 쓰는 방식에만 익숙해져 있어서 신경 쓰지 않으면 버릇처럼 자연스럽게 적어버리는 것 같습니다.

2024-04-02 09:21 UTC, leeshin20 commented on src/main/java/chess/Position.java
> +    }
equals 메서드를 재정의하여 비교하고자 하는 두 Position 객체가 논리적으로 같은지를 판단합니다.

하지만 hash 값을 사용하는 컬렉션을 사용하는 경우에는 equals메서드 뿐 아니라 hashCode메서드 두 가지가 모두 true일 때 동일한 객체라고 판단하게 되는데, hashCode메서드는 객체가 가지는 고유한 주소의 값을 int로 변환하기 때문에 객체 마다의 고유한 다른 값을 리턴하여 다른 객체로 판단하게 됩니다.

따라서 위와 같이 hashCode 메서드를 재정의 해야, 전달 받은 `row`, `column`의 값으로 해시를 생성하기 때문에 객체의 비교가 정확히 이루어지게 됩니다.

2024-04-02 09:31 UTC, leeshin20 commented on src/main/java/chess/Position.java
> +        this.column = column;
익숙하지 않다고 대충 넘기지 말고 요구사항을 꼼꼼하게 확인하겠습니다.

TDD로 구현하는 부분은 일단 기능을 구현하는데 급급하여 테스트를 작성을 미루거나 지키지 않게 되는데
작은 단위의 실패 테스트 작성 -> 테스트를 통과할 수 있는 코드 작성 -> 리팩토링
의 단계를 지켜서 기능들을 TDD로 구현할 수 있도록 노력하겠습니다

원시 값도 버릇처럼 사용하지 않도록 의식하겠습니다!

2024-04-02 09:42 UTC, leeshin20 commented on src/test/java/chess/PositionTest.java
> +    }
1. 새로운 포지션을 설정해주는 기능의 테스트여서 별 생각없이 set을 붙인 것 같습니다.
2. 말씀하신대로 기본적인 기능의 작동 유무만 테스트 하기 보다는, 하나의 기능에서 파생되어 발생할 수 있는 다양한 문제점을 파악하고, 테스트 코드를 작성해나가며 기능을 보완하는 것이 중요하다 생각이 됩니다.
3. 만들 때는 해당 getter가 테스트 코드에만 사용되는 것을 인지하지 못 했는데, 이런 코드는 불필요하며, 좋지 않다고 생각합니다!

2024-04-05 12:06 UTC, poi1649 commented on src/main/java/chess/Board.java
> +        board.put(new Position('H',7), new Piece(Piece.Type.PAWN, Piece.Team.BLACK));
훌륭합니다. 
초기위치 같은 것도 Type enum에 책임을 넘길 수도 있겠네요!

2024-04-05 12:06 UTC, poi1649 commented on src/main/java/chess/Position.java
> +    }
굿굿..
여기서 추가 과제 하나만 내겠습니다.
동일성과 동등성에 차이에 대해서 4월 10일 23:59 까지 블로그 글 작성해주세요!

2024-04-05 12:07 UTC, poi1649 commented on src/main/java/chess/ui/OutputView.java
> +        for (int row = 8; row >= 1; row--) {
대체하는 습관을 길러주세요

2024-04-05 12:17 UTC, poi1649 requested changes
코드가 훨신 좋아진게 느껴져서 감동이네요.. 고생 많으셨습니다.🫡

그런데 본격적인 로직을 짜기 전에 아주 조금만 더 잡고 가면 좋을 것 같아서 RC 한번만 더 드리겠습니다. 
주말 잘 보내시고 4/10 수요일 23:59 까지 리뷰 반영해주세요~~

2024-04-05 12:17 UTC, poi1649 commented on src/main/java/chess/board/Board.java
> +            board.put(new Position(file, 2), new Piece(Type.PAWN, Team.WHITE));
1, 2 같은 포지션도 매직넘버입니다. 
상수로 분리하기에 너무 많다고 느껴지셔서 놔두신걸까요?

2024-04-05 12:17 UTC, poi1649 commented on src/main/java/chess/piece/Piece.java
> +    }
도메인 클래스에 여전히 view와 관련한 로직이 남아있네요 한 번만 더 고민해봅시다.

2024-04-05 12:17 UTC, poi1649 commented on src/main/java/chess/position/File.java
> +                .orElse(null);
null을 반환하기 vs `orElseThrow`로 예외 던지기 
어떤 장단점이 있을까요

+ 별개로 스트림 사용은 굉장히 훌륭합니다. 코드가 훨신 보기 편하지 않나요?

2024-04-05 12:17 UTC, poi1649 commented on src/main/java/chess/position/Position.java
> +        this.rank = Rank.findByValue(rank);
원시값 포장 👍👍👍👍👍
어떤 장점이 있을까요?

2024-04-05 12:17 UTC, poi1649 commented on src/main/java/chess/position/Position.java
> +                file == position.file;
여기서 equals 가 아닌 == 연산자로 비교할 수 있는 이유가 뭘까요?

2024-04-05 12:18 UTC, poi1649 commented on src/main/java/chess/board/Board.java
> +    private void initializeBlackPiece() {
메서드 이름이 훨신 적절해진 것 같네요!

2024-04-05 12:18 UTC, poi1649 commented on src/main/java/chess/board/Board.java
> +    public void initializeBoard() {
Board가 생성될때 만드시 호출되어야만한다면 생성자에 넣어줘도 괜찮은 것 아닐까요? 보드의 초기화도 밖에서 반드시 호출할 필요가 있을까요?

2024-04-10 12:43 UTC, leeshin20 commented on src/main/java/chess/Board.java
> +        board.put(new Position('H',7), new Piece(Piece.Type.PAWN, Piece.Team.BLACK));
`StartPiecePosition` enum 클래스를 따로 만들어서 관리하도록 수정했습니다!

2024-04-10 12:47 UTC, leeshin20 commented on src/main/java/chess/board/Board.java
> +            board.put(new Position(file, 2), new Piece(Type.PAWN, Team.WHITE));
상수로 분리하면 너무 많아질 것 같다고 생각이 되어 수정하지 않았습니다.

해당 하는 부분의 매직넘버를 모두 상수로 대체하였습니다!

2024-04-10 13:37 UTC, leeshin20 commented on src/main/java/chess/position/File.java
> +                .orElse(null);
`.orElse(null)`로 null을 리턴한다면, 비교적 코드가 간결해져서 작성하기가 편하며, 예외 처리에 대한 추가적인 코드가 없어도 된다는 장점이 있습니다.

하지만 어떤 예외가 발생하던 null이 반환되기 때문에 실제로 오류가 발생했을 때, 원인을 찾는데 비교적 시간이 걸릴 수 있습니다.

하지만 `orElseThrow`를 사용한다면 명확하게 예외에 대한 상황을 명시하기 때문에 문제가 발생했을 때, 디버깅 과정에서 오류를 빠르게 파악하고 처리할 수 있다는 장점이 있습니다.

스트림을 사용하지 않고, foreach와 if 문을 사용하여 구현하는 방법도 고민을 해 보았지만, 들여쓰기가 2단 이상 들어가기 때문에 최대한 간결하게 작성할 수 있는 방법을 찾아보다가 스트림을 사용하게 되었습니다.
다양한 경우에서 사용해보며 좀 더 익숙해져야겠지만, 확실히 해당 코드를 좀 더 간결하게 작성할 수 있었고 코드를 읽기 편하다고 느껴집니다!!

2024-04-10 13:55 UTC, leeshin20 commented on src/main/java/chess/position/Position.java
> +        this.rank = Rank.findByValue(rank);
원시값을 포장한다면
`Position`클래스에서 원시값 `file`,`rank`를 사용하지 않고, 
포장하여 `File`,`Rank`클래스로 분리하게 된다면, `file``rank`의 값을 `Position`에 넘기지 않고 직접 관리할 수 있게 되어 책임이 명확해지며, 각 엔티티를 작게 유지할 수 있습니다.

입력 값에 대한 검증이나, 각종 기능의 로직이 변경되더라도, 원시값을 포장한 클래스만 수정하면 되기 때문에 유지보수에도 도움을 줍니다.

2024-04-10 14:00 UTC, leeshin20 commented on src/main/java/chess/board/Board.java
> +    public void initializeBoard() {
보드가 생성될 때 함께 초기화 되는 경우 말고, 보드의 상태를 초기화 시키는 다른 경우가 있지 않을까 싶어서 밖에서 호출을 했는데, 지금 생각해보니 그런 경우가 있을까 싶은 생각이 듭니다.

생성자와 함께 호출되도록 수정했습니다!

2024-04-10 14:04 UTC, leeshin20 commented on src/main/java/chess/position/File.java
> +                .orElse(null);
`.orElseThrow(() -> new IllegalArgumentException("잘못된 Rank 입력입니다(1~8)"));`
해당 부분에 작성된 예외 메시지도 `start`, `end` 입력을 상수로 관리해준 것 처럼,
상수로 따로 관리하도록 하는 것이 좋을지 여쭤봅니다

2024-04-10 14:21 UTC, leeshin20 commented on src/main/java/chess/piece/Piece.java
> +    }
출력과 관련된 메서드를 분리했지만,
출력을 담당하는 클래스에서 `Piece`의 `Team`, `Type` 정보를 가져오기 위해
`getType()`, `getTeam()` 를 사용하여 게터를 쓰지 않는다는 요구사항이 위배 되었습니다.

일부 게터 사용이 허용되는 경우가 있는 것인지, 아니면 이 경우에도 게터를 사용하지 않고 완전히 구현할 수 있는 방법이 있는지 궁금합니다.

2024-04-10 14:52 UTC, leeshin20 commented on src/main/java/chess/Position.java
> +    }
블로그 글입니다!
https://velog.io/@leeshin20/%EB%8F%99%EC%9D%BC%EC%84%B1Identity-%EB%8F%99%EB%93%B1%EC%84%B1Equality

2024-04-10 14:58 UTC, leeshin20 commented on src/main/java/chess/position/Position.java
> +                file == position.file;
`rank`와 `file`이 int 같은 원시타입 이었다면, 서로 같은 값을 가지는지 비교하기 위해 `equals`메서드를 사용했을 것 입니다.
하지만 `rank`와 `position.rank`는 Rank 타입의 열거형 상수를 참조하고 있습니다.
비교하려는 두 값이 같은 값을 가지고 있다면, 실제로는 동일한 열거형 상수를 참조하고 있을 것이기 때문에 `==` 연산자를 사용하여도 정상적으로 비교를 할 수 있습니다.

2024-04-10 14:59 UTC, leeshin20 commented on src/main/java/chess/board/Board.java
> +    private void initializeBlackPiece() {
메서드 이름을 축약해서 간결하게 표기하기 보다 의미를 명확하게 할 수 있도록 신경쓰겠습니다!

2024-04-14 05:09 UTC, poi1649 approved these changes
1단계 고생하셨습니다. 충분히 깔끔해진 것 같네요! 다음 단계 넘어가시죠

2024-04-14 05:09 UTC, poi1649 commented on src/main/java/chess/board/Board.java
> +    public void initializeBoard() {
좋습니다. 추가로 생성자에서만 사용하도록 private 으로 바꿔줘도 좋겠네요

2024-04-14 05:25 UTC, merged