[1단계 - 체스판 초기화] 이준섭 미션 제출합니다.
poi1649/java-chess pull request #2
Opened 2024-04-02 17:45 UTC by junseoplee

2024-04-05 15:02 UTC, poi1649 requested changes
굉장히 어려웠을텐데 고생많으셨습니다💯 
커멘트 몇 개 남겼으니 4월 10일 23:59 까지 반영하고 다시 요청 주세요! 주말 잘 보내세요~

2024-04-05 15:02 UTC, poi1649 commented on src/test/java/chess/model/CommandTest.java
> +  void 게임_시작_명렁어_입력이_올바르지_않다면_예외_처리한다() {
오 DisplayName을 사용해주셨네요. 
메서드 이름이 이미 한글인데 DisplayName을 한 번 더 써주면 어떤 이점이 있을까요??

2024-04-05 15:02 UTC, poi1649 commented on README.md
> +- [x] 게임 시작 명령어는 start, 종료는 end 입력이 올바르지 않다면 예외 처리한다
TDD를 의식적으로 하려고 한 게, 커밋 단위에서 보여서 좋네요...🥲👍

그런데 테스트가 통과하지 않는 코드를 그대로 커밋하는 것은 조금 위험할 수 있습니다.
프로덕션에 돌아가지 않는 코드가 배포될 수 있으니, 배포에 관점에서 위험성은 말할 것도 없겠죠?

또한 협업의 관점에서도 위험성이 있습니다. 
커밋은 협업의 최소 단위입니다. 다른말로 하면 커밋이 된 코드는 외부 저장소에서 동료가 접근할 수 있는 코드입니다.(푸쉬가 됐다고 가정) 
그런데 만약 동료가 테스트가 통과하지 않는 코드를 pull 을 받았고, 어떤 기능을 추가한 후 테스트를 실행한다면 어떤 일이 벌어질까요? 계속해서 엄한 부분을 수정하느라 생산성이 저하될 수도 있고, 최악의 경우 테스트 통과를 위해 자신의 로직을 잘못된 방향으로 수정할 수도 있습니다.

그럼 TDD에서 커밋 단위는 어떻게 하는게 좋을까요? 이 부분은 한 번 고민해보시고 답글 달아주세요!

2024-04-05 15:02 UTC, poi1649 commented on src/test/java/chess/model/position/FileTest.java
> +        .isInstanceOf(IllegalArgumentException.class);
`@parameterizedTest `를 이용하여 더 다양한 케이스를 테스트해 볼 수도 있습니다!
경계값 테스트도 있으면 좋겠네요!

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/model/position/File.java
> +  FILE_H('h');
Enum으로 관리하는거 좋네요 👍👍 사용자의 실수를 확실히 방지할 수 있을 것 같습니다.

그런데 enum의 값들을 `FILE_x` 처럼 쓰게되면 이를 밖에서 사용할 때, FILE.FILE_A 으로 사용하게 됩니다. 
`FILE.A` 로 쓰더라도 충분히 의미가 전달될 수 있지 않을까요!?

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/model/position/File.java
> +                 .orElseThrow(() -> new IllegalArgumentException(ErrorMessage.MISMATCH_ARGUMENT.getMessage()));
오.. 에러 메시지를 분리해주셨네요. 혹시 해당 클래스에 쓰지 않고 별도의 클래스를 만들어 에러메시지를 관리하는 이유를 공유해줄 수 있나요?

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/model/position/Rank.java
> +  }
스트림 사용이 적절하네요 💯💯💯

그런데 혹시 findFirst와 findAny의 차이 기억하시나요? ㅎㅎ

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/view/ErrorMessage.java
> +  MISMATCH_ARGUMENT("[ERROR] 잘못된 규격입니다.");
조금 더 명확한 에러 메시지를 내려주는 것도 좋아보입니다! 
에러 메시지를 왜 상세하게 써줘야하는지도 고민해봐도 좋을 것 같네요

2024-04-05 15:02 UTC, poi1649 commented on README.md
> +- [x] 체스판의 가로는 왼쪽부터 a ~ h로 구현한다
계속해서 문서 업데이트 해주는 거 좋습니다 👍 
문서도 코드의 일부죠

2024-04-05 15:02 UTC, poi1649 commented on src/test/java/chess/model/piece/PieceTest.java
> +    }
추상 클래스를 테스트해주려고 만들어준 클래스로 보이네요!
몇가지 질문을 드리고 싶습니다.
1. 인터페이스가 아닌 추상 클래스로 만드신 이유가 뭔가요?
2. 추상 클래스에 대한 테스트가 꼭 필요할까요?

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/model/position/InitialPosition.java
> +  private final int rank;
file과 rank 클래스가 이미 존재하는데, 원시값으로 써주신 이유가 있나요?!

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +          processCommand();
start 를 계속 입력하면 계속 체스판이 출력되네요!
예상치 못한 동작 같습니다

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/view/OutputView.java
> +      final int row = rank.getValue();
한 번에 원시값을 get 해주는 것과 지금처럼 get을 두 번 거치는 것에 어떤 장단점이 있을까요?

2024-04-05 15:02 UTC, poi1649 commented on src/test/java/chess/model/board/InitialBoardTest.java
> +  }
블랙킹의 위치만 확인해주면 충분할까요?

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/model/position/InitialPosition.java
> +
원시값을 포장한 클래스가 이미 있는데, 원시값으로 써주신 이유가 있나요??

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/model/position/InitialPosition.java
> +  BLACK_PAWN_H(8, 7);
고통스럽겠지만, 한 번 중복코드를 줄여보시고, 이 구조와 그 구조 사이에 어떤 장단점이 있는지 고민해보세요!🦅

2024-04-05 15:02 UTC, poi1649 commented on src/main/java/chess/view/Symbol.java
> +    }
출력 책임 분리를 위한 별도의 enum 이군요♞ 좋은 시도 같습니다!
그런데 이미 각 Piece들의 클래스를 이 enum에서 참조하게 되었으니 각 Enum 객체들이 클래스를 직접 갖게하여, 더 깔끔하게 코드를 리팩터링 할 수 있을 것 같네요!
힌트 : `KING_WHITE("k", King.class)`

그리고 이 케이스에는 그렇게 와닿지 않는 예시일 수 있지만, instance of 또는 getClass 를  지양해야하는 이유를 한 번 찾아보시죠!

2024-04-08 14:17 UTC, junseoplee commented on src/test/java/chess/model/CommandTest.java
> +  void 게임_시작_명렁어_입력이_올바르지_않다면_예외_처리한다() {
테스트 결과 창에서 테스트 클래스 혹은 메서드의 이름을 한글로 지정해서 보일 수 있습니다.
또한 "" 안에서 문법을 자유롭게 쓸 수 있기 때문에 가독성을 높일 수 있습니다.
즉 의도 표현을 더 명확하게 할 수 있다는 이점이 있습니다!

2024-04-08 14:40 UTC, junseoplee commented on README.md
> +- [x] 게임 시작 명령어는 start, 종료는 end 입력이 올바르지 않다면 예외 처리한다
지적 감사합니다.
진행 도중에 방향을 완전 바꿔버려서 이전에 통과했던 테스트를 잊고 있었네요ㅜ

TDD에서 커밋 단위는 기능(메서드) 단위로 해야 한다 생각합니다. 
또한 그 기능은 최대한 작은 단위로 커밋해야합니다. 
왜냐하면 협업에서는 각 커밋으로 어떤 추가, 변경 사항이 있는지 확인하기 때문입니다. 
단위가 작다면 추후 문제 발견 시 문제를 찾고 수정하기 용이해집니다.

보다 잘 지키도록 해보겠습니다.
이번에는 클래스 전체를 테스트한다는 개념으로 접근해서 올바른 TDD에서 조금 멀었습니다.
특정 기능을 만든다기 보다는 전체적으로 설계하기 때문에 생각도 많이 꼬였네요.

의문이 있습니다. 최소 기능 단위로 커밋을 한다면 테스트 코드로 최소 기능 단위로 만들어야할까요(기능에 필요한 메서드 별로)? 
느껴지기에 복잡한 클래스라면 우선 기능을 구현하기 위한 전체적인 틀을 설계하고, 그 기능에 필요한 메서드들을 다시 구상할텐데 이러면 테스트 코드 구현 단계에서 클래스 설계가 완전히 끝나 있어야 하는건가요?

아니라면,
TDD 커밋 단위 레드 - 그린 - 리팩토링을 본다면 우선 간단하게 통과하는 기능을 만든 후 리팩토링을 계속합니다. 이 리팩토링 단계에서 기능을 보다 의미있는 메서드 단위로 정리하는 작업을 하면 될까요?

2024-04-08 14:57 UTC, junseoplee commented on src/test/java/chess/model/position/FileTest.java
> +        .isInstanceOf(IllegalArgumentException.class);
오 @parameterizedTest 를 이용하면 다양한 케이스를 테스트할 수 있네요 경계 값 테스트를 추가했습니다.

2024-04-08 14:57 UTC, junseoplee commented on src/main/java/chess/model/position/File.java
> +  FILE_H('h');
좋아요!

2024-04-08 15:06 UTC, junseoplee commented on src/main/java/chess/model/position/File.java
> +                 .orElseThrow(() -> new IllegalArgumentException(ErrorMessage.MISMATCH_ARGUMENT.getMessage()));
사용자에게 보여지는 것은 view에 모두 모아두고 싶었어요.
그리고 따로 열거형을 만든다면 에러메세지의 수정, 추가 등 관리가 용이해집니다!
가장 중요한 것은 값들의 열거라는 목적성이 보인다는 점입니다!

2024-04-08 15:56 UTC, junseoplee commented on src/main/java/chess/model/position/Rank.java
> +  }
ㅎㅎㅎ 원래 findAny 였다가 findFirst로 변경했어요
순서가 중요하지 않은 병렬 스트림에서 findAny 의 사용이 더 효율적일 수 있습니다. 
첫 번째 요소를 찾는 것보다 더 빨리 완료될 수 있는 요소를 반환할 수 있죠.

이런 비용 측면에서 직렬 스트림을 생성하는 것 보다 병렬 스트림 생성의 비용이 더 클 수 있기 때문에 이런 간단한 작업에서는 findFirst가 더 유리하다고 볼 수 있습니다

정리하자면 병럴 처리의 이점을 얻기 위한 상황이 아니고, 순서도 중요하기 때문에 findFirst를 사용했습니다!

2024-04-08 16:00 UTC, junseoplee commented on src/main/java/chess/view/ErrorMessage.java
> +  MISMATCH_ARGUMENT("[ERROR] 잘못된 규격입니다.");
에러 메세지가 출력됐을 때 어디에서 문제가 생겼는지 보다 명확하게 알 수 있기 때문입니다.

2024-04-08 16:10 UTC, junseoplee commented on src/test/java/chess/model/piece/PieceTest.java
> +    }
1. 추상 클래스는 그 추상 클래스를 상속 받아서 기능을 이용하고 확장시킵니다. 공통점들을 모아 추상화하여 만든 클래스입니다. 즉 중복된 요소들을 통합 및 확장할 수 있습니다.
따라서 추상 클래스를 클래스간의 연관 관계를 구축하는 것에 주요 기능을 합니다.
인터페이스는 공통 기능을 사용하기 위해 사용한다 생각합니다.
2. 추상 클래스에 대한 테스트 역시 필요하다 생각합니다.
추상 클래스의 구현이 변경되었을 때 하위 클래스에 부정적인 영향이 없는지 확인할 수 있습니다.

2024-04-08 16:25 UTC, junseoplee commented on src/main/java/chess/model/position/InitialPosition.java
> +  private final int rank;
우선 이 클래스는 초기 위치를 열거하는 목적으로 만들어졌습니다.
피스의 위치를 초기화할 때는 원시값이 매개변수로 들어가야합니다.
따라서 이 클래스에서는 포지션을 초기화할 때 바로 사용할 수 있도록 원시값으로 썼습니다.
왜냐하면 단순 열거에서는 굳이 객체로 포장해서 추가적인 복잡성을 올릴 필요는 없다 판단했기 때문입니다.

2024-04-08 16:31 UTC, junseoplee commented on src/main/java/chess/controller/ChessController.java
> +          processCommand();
아 그런 요구사항이 있는지는 몰랐습니다. 저는 start 를 입력하면 체스판을 새로 초기화하여 새 게임을 시작하는 방식으로 이해했습니다.
start 를 입력받은 상태에서 다시 start 를 입력받았을 때는 체스판이 다시 초기화되어 출력되지 않고(무시하고, 에러메세지 출력) end 가 입력됐을 때 만을 인식하여 종료되도록 바꿀까요?

2024-04-09 05:55 UTC, junseoplee commented on src/main/java/chess/view/OutputView.java
> +      final int row = rank.getValue();
get을 해주면 객체의 특정 부분에 대한 접근만을 허용합니다. 내부의 노출을 최소화하여 캡슐화를 지킬 수 있어요. 객체의 내부 구조가 변경되어도 보여지는 것은 변함이 없어 편리하겠네요.
단점은 코드의 직관성이 떨어질 수 있습니다. 그리고 추가적인 연산을 하기 때문에 작지만 성능적인 손해가 발생할 수 있겠네요.

2024-04-09 11:03 UTC, junseoplee commented on src/test/java/chess/model/board/InitialBoardTest.java
> +  }
전체 체스판이 초기화되는 것을 전부 테스트하기는 어려워 대표적으로 블랙킹만 테스트하려 했습니다.
또한 클래스 기능 전체를 테스트하기 보다는 이 기능에 필요한 각 메서드들을 각각 테스트 하는 게 좋지 않을까 생각합니다.

우선 해당 테스트코드에는 클래스의 목적 그대로 체스판 초기화가 올바르게 됐는지 확인하는 테스트코드를 작성해봤습니다.

2024-04-09 11:07 UTC, junseoplee commented on src/main/java/chess/model/position/InitialPosition.java
> +
위와 같습니다!

2024-04-09 11:18 UTC, junseoplee commented on src/main/java/chess/model/position/InitialPosition.java
> +  BLACK_PAWN_H(8, 7);
PAWN 을 줄이는 방법일까요? 혹은 BLACK 과 WHITE 의 랭크를 줄이는 방법일까요?
조건과 반복문을 사용해서 코드를 줄일 수 있다고는 생각하는데 굳이 그래야할 이유를 모르겠습니다.
이렇게 열거하면 목적성도 보이고 확장과 수정도 편리하고 추가적인 비용도 줄어든다고 생각합니다.
가장 중요한 것은 어떤 피스가 어떤 위치를 갖고 있는지 확인하기 편합니다.

2024-04-09 17:36 UTC, junseoplee commented on src/main/java/chess/view/Symbol.java
> +    }
이 생각은 못했어요! 감사합니다!! 덕분에 불필요했던 코드를 대폭 줄일 수 있었습니다. 뿌듯해요ㅋㅋ

상속 관계에서 해당 메서드를 사용할 수 있습니다. 추상화된 Piece 가 특정 말 일 경우에만 처리하는 로직을 구현할 수 있게 합니다. 하지만 이것은 추상화 계층을 깨게됩니다. 
추상화 계층을 사용하는 외부에서는 하위를 알 필요가 없습니다. 
하지만 이 경우는 직접적으로 알 수 있게됩니다. 캡슐화에서 알면 안되는 것입니다.
상위 계층의 Piece 가 아닌 하위 클래스를 사용하여 추상화가 깨지고 하위 클래스의 로직을 알 수 있게 되기 때문에 캡슐화가 깨집니다.

새로운 클래스가 추가될 때(확장)에 많은 비용이 들어가며 확장이 어려워 개방 폐쇄 원칙에 위배됩니다.
또한 Piece의 메서드가 하위 클래스가 가져야할 책임을 모두 갖게 되기 때문에 단일 책임 원칙에 위배됩니다.

객체에게 물어봐서 확인하도록 합시당

2024-04-14 05:09 UTC, poi1649 commented on src/test/java/chess/model/CommandTest.java
> +  void 게임_시작_명렁어_입력이_올바르지_않다면_예외_처리한다() {
좋습니다! 그런데 지금은 테스트 메서드랑 이름이 완전 동일해서 큰 효과는 없긴 하겠네요

2024-04-14 05:13 UTC, poi1649 commented on README.md
> +- [x] 게임 시작 명령어는 start, 종료는 end 입력이 올바르지 않다면 예외 처리한다
두 방향 다 괜찮은 방향인 것 같아요.
말씀해주신 것처럼 처음부터 도메인에 대한 이해도가 뛰어나다면 복잡한 로직이라도 쉽게 기능을 쪼갤 수 있지만, 그렇지 않은 경우 처음부터 잘 쪼개는건 불가능합니다.

이 때, 위에 써주신 것처럼 큰 틀을 만들어보는 것, 아니면 간단한 기능을 만들어보는것 어느 방법으로든 방향을 잡기만 하면 됩니다.
정답은 없으니, 본인이 기능을 더 잘이해할 수 있는 방향으로 선택하시면 좋을 것 같아요!

2024-04-14 05:14 UTC, poi1649 commented on src/main/java/chess/model/position/Rank.java
> +  }
훌륭합니다👍👍👍👍👍

2024-04-14 05:15 UTC, poi1649 commented on src/test/java/chess/model/piece/PieceTest.java
> +    }
근거가 확실하네요!

추가로 [이 글](https://tecoble.techcourse.co.kr/post/2020-05-18-inheritance-vs-composition/) 한 번 읽어보세요!

2024-04-14 05:16 UTC, poi1649 commented on src/main/java/chess/model/position/InitialPosition.java
> +  private final int rank;
확실히 배보다 배꼽이 커질 수 있겠네요.
실수가 아니고 본인이 확실하게 고민한 결과라면 좋습니다!👍

2024-04-14 05:16 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +          processCommand();
음 이 부분은 지금은 확실히 모호할 수 있겠군요. 2단계 요구사항을 보시고 수정해주셔도 좋겠어요!

2024-04-14 05:19 UTC, poi1649 commented on src/main/java/chess/view/OutputView.java
> +      final int row = rank.getValue();
좋습니다! 
추가로,저는 내부 객체를 꺼낼 일이 있다면 객체에 메시지를 던지지 않고 있는 게 아닌지 의심해볼 필요가 있다고 생각합니다.

원시값을 꺼내는 getter만 배치시키면 output 로직을 제외한 곳에서 getter를 사용하지 않을 수 있게 방지해주는 역할도 해줄 수 있지않을까요?

2024-04-14 05:24 UTC, poi1649 commented on src/main/java/chess/model/position/InitialPosition.java
> +  BLACK_PAWN_H(8, 7);
음 물론 굳이 그래야할 필요 없다고 느낄 수 있습니다. 
그렇지만 지금은 프로덕트를 만드는 게 아니고 공부하고 있는 과정이니 커멘트를 남겨 봤네요

추상화를 통해 중복을 줄일 수 있는데 줄이지 않는 것과, 할줄 몰라서 줄이지 못하는 것은 다릅니다. 
실제 프로덕트를 만들면서 이런 고민들에 많이 마주치게 될텐데 그 때 고민하는 것보다는 지금 미리 시도해보고 자기만의 주관을 세우는게 중요하다고 생각하기 때문에, 웬만한 시도는 해보시는걸 추천드려요

2024-04-14 05:25 UTC, poi1649 approved these changes
커멘트의 자기 의견을 잘 남겨주는 게 너무 좋네요. 항상 저도 더 고민하고 배워가는 것 같습니다.
1단계 고생하셨고 2단계 고고하시죠

2024-04-14 05:25 UTC, merged