[2단계 - 말 이동] 이준섭 미션 제출합니다.
poi1649/java-chess pull request #4
Opened 2024-05-06 12:19 UTC by junseoplee

2024-05-12 10:51 UTC, poi1649 requested changes

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +    this.board = initialBoard.createInitialBoard();
보드의 생성책임 분리 좋네요 👍 
이런 패턴을 팩토리 메서드 패턴이라고도 부릅니다. 
관련한 내용 공부해보셔도 좋아요

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +    }
String 대신 Command 라는 객체나 Enum을 만들어보는건 어떻게 생각하시나요?

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +    }
List<String> receivedMoveOrEndCommand = inputView.receiveMoveOrEndCommand();
        if (receivedMoveOrEndCommand.get(0).equals(END_COMMAND)) {
        
이런 복잡한 문제를 해당 객체로 넘겨줄 수도 있을 것 같아요

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +        Position targetPosition = parsePosition(receivedMoveOrEndCommand.get(1));
0, 1 같은 매직넘버도 상수로 습관적으로 치환해주는 게 좋아보이네요!

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/board/Board.java
> +    return Map.copyOf(board);
방어적 복사를 하려고 했군요 👍👍 다만 현재 Map의 키, 값 전부 객체이기 때문에 copyOf 사용만으로는 완전히 복사되지는 않겠네요.

원래 목적이 Map의 수정을 방지하는 것이라면 문제 없겠지만, 객체가 불변이라는 게 보장이 안되는 상황에서는 다른 방법이 필요해요

왜 그런지 내용이 궁금하다면 deep copy와 shallow copy에 대해 공부해보셔도 좋습니다!

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/board/Board.java
> +
꼼꼼한 검증 굿입니다 👍

++ 그런데 validateIsFromEmpty 보다는 validateFromNotEmpty or validateNotEmpty(from) 가 더 적절하지 않을까요? 지금은 `from이 비어있는지 검증한다` 로 오독할 여지가 있어보이네요

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/board/Board.java
> +  }
1. `자신의 기물인지 검증`하는 메서드 맞을까요? 여기도 더 적절한 이름이 있을 것 같네요 🤔
2. getter 사용을 지양하라는 프로그래밍 조건이 있었던 걸로 기억합니다. 이런 경우 어떻게 해결할 수 있을까요?

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/piece/pieces/Bishop.java
> +
각 Piece가 자신의 움직임을 가지게 했네요 
좋은 방법 같습니다! 💯
이 방법에 어떤 장점과 어떤 단점이 있을지 정리 한 번만 부탁드려요!

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/position/Position.java
> +  }
position과 movement가 서로 의존하고 있네요. (position도 Movement를 사용하고, Movement도 position 을 사용함)
이런 상황을 양방향의존이라고 부릅니다.
객체의 양방향 의존에는 어떤 문제가 있고, 어떻게 해결할 수 있을까요?

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/position/Position.java
> +  }
엇 ㅋㅋㅋㅋ 직접 작성했군요.👍 사실 잘 만들어진 java 내부 라이브러리도 있습니다! ㅋㅋㅋㅋ

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/view/InputView.java
> +  }
시작하자마자 게임을 종료할 수는 없나요?

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/view/InputView.java
> +    }
1. 상수 분리 해주세요!
2. 완전히 이상한 입력 ex.`move ㅇ! ㅋㅋ` 이 올 경우 이 입력의 검증 책임은 어디에 있을까요?

2024-05-12 10:51 UTC, poi1649 commented on src/test/java/chess/model/board/BoardTest.java
> +  }
적절한 라이브러리 사용👍

2024-05-12 10:51 UTC, poi1649 commented on src/test/java/chess/model/piece/pieces/KingTest.java
> +  }
실패하는 테스트만 작성한 프로그램을 믿을 수 있을까요?

2024-05-12 10:51 UTC, poi1649 commented on src/test/java/chess/model/piece/pieces/PawnTest.java
> +
굉장히 꼼꼼한 테스트 좋습니다. 폰처럼 어려운 기물일수록 이런 꼼꼼한 테스트 작성이 필요하죠! 👍

2024-05-12 10:51 UTC, poi1649 commented on src/test/java/chess/model/piece/pieces/PawnTest.java
> +    Pawn pawn = new Pawn(fromRank == 2 ? Color.WHITE : Color.BLACK);
color 까지 csv source로 포함시키는건 어떨까요?

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/board/Board.java
> +  }
체스 게임에서 가장 핵심적인 기능인 move에 대한 테스트가 부족하네요 테스트 케이스 작성이 필요하지 않을까요?

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/piece/pieces/King.java
> +import chess.view.ErrorMessage;
model 패키지가 view에 의존하고 있네요. 의존의 방향은 어떻게 설계하는게 좋을까요?

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/piece/Piece.java
> +    }
1. other이 null 인 경우 현재의 에러 메시지가 적절할까요?
2. null이 애초에 Piece 안으로 흘러들어와도 괜찮을까요? null은 어떨 때 발생하나요?

2024-05-12 10:51 UTC, poi1649 commented on src/main/java/chess/model/piece/pieces/Pawn.java
> +    // Pawn의 경우 목적지에 도착했을 때 색 검사를 하지 않음
혹시 pawn은 왜 목적지의 기물 색을 검사하지 않나요?

2024-05-13 02:42 UTC, junseoplee commented on src/main/java/chess/controller/ChessController.java
> +    this.board = initialBoard.createInitialBoard();
팩토리 메서드 패턴은 객체 생성 로직을 별도의 메서드나 클래스로 추출하여 캡슐화하는 디자인 패턴입니다.
새로운 객체 생성 방식이 필요한 경우 팩토리 메서드만 수정하면 되므로 클라이언트 코드에 영향을 주지 않습니다.
유연성이 생기고 의존성이 감소합니다
`ChessControll`는 생성 과정에 대한 세부 사항을 알 필요가 없습니다

2024-05-13 02:48 UTC, junseoplee commented on src/main/java/chess/controller/ChessController.java
> +    }
좋은 방향입니다!(사실 이전에 이미 Command 클래스가 있었어요ㅋㅋ)

2024-05-13 02:48 UTC, junseoplee commented on src/main/java/chess/controller/ChessController.java
> +        Position targetPosition = parsePosition(receivedMoveOrEndCommand.get(1));
네!!

2024-05-13 04:38 UTC, junseoplee commented on src/main/java/chess/model/board/Board.java
> +    return Map.copyOf(board);
맵의 키와 값을 새로운 맵으로 복사하여 반환하지만, 이는 shallow copy에 해당합니다. 
맵의 키와 값이 참조하는 객체 자체는 복사하지 않고, 해당 객체에 대한 참조만 복사합니다.
따라서 Position이나 Piece와 같은 객체가 불변이 아니라면, 외부에서 해당 객체를 수정할 경우 복사된 맵에도 영향을 줄 수 있습니다.
완전한 방어적 복사를 위해서는 deep copy가 필요합니다. 
deep copy는 객체 자체를 복사하여 새로운 객체를 생성하는 것을 의미합니다. 
이를 위해서는 Position과 Piece 클래스에 적절한 복사 생성자나 복사 메서드를 구현해야 합니다.

2024-05-13 05:15 UTC, junseoplee commented on src/main/java/chess/model/board/Board.java
> +
그럴 수 있겠네요. 비어있으면 안된다는 걸 명시적으로 나타내야하니까 `validateNotEmpty(from)`이 적절해보여요.

2024-05-13 05:33 UTC, junseoplee commented on src/main/java/chess/model/board/Board.java
> +  }
진영(Color)에 따라 번갈아가며(turn) 기물을 움직일 수 있습니다.
이때 움직이고 싶은 기물이 자신의 turn에 맞는지 확인하는 메서드입니다.
`validateTurn`이 적절해보입니다.
Piece 클래스에 턴 유효성 검사 메서드를 넣고
Board에서는 이 메서드를 직접 호출하여 검사하는 것으러 처리합니다.
이렇게 되면 Board 클래스는 Piece의 color에 직접 접근하지 않고 Piece 객체에게 책임을 위임합니다. 캡슐화를 유지하고 객체 결합도를 낮출 수 있습니다.

2024-05-13 05:42 UTC, junseoplee commented on src/main/java/chess/model/piece/pieces/Bishop.java
> +
장점:
피스 클래스의 변경이 다른 부분에 영향을 미치지 않습니다.
피스 이동에 대한 세부 사항을 외부에 알리지 않아 캡슐화의 장점이 있습니다.
관련 메서드가 클래스 내부에 함께있기에 응집도가 증가합니다.
확장성과 유지보수성이 증가합니다.
단점:
코드 중복이 있을 수 있습니다.

2024-05-13 08:21 UTC, junseoplee commented on src/main/java/chess/model/position/Position.java
> +  }
Position이 변경될 때 Movement에 영향이 있을 수 있고,
반대로 Movement가 변경될 때 Position에 영향이 있을 수 있어 유지보수와 확장성에 문제가 생깁니다.
예를 들어 A와 B가 있다 하고 서로 양방향 의존 관계입니다.
여기서 A를 생성하기 위해서는 B의 생성이 필요하고, B를 생성하기 위해서는 A의 생성이 필요한 문제가 생길 수 있습니다.

MovementConverter 클래스를 생성하여 양방향 의존성과 책임을 분리했습니다.

2024-05-13 08:43 UTC, junseoplee commented on src/main/java/chess/model/position/Position.java
> +  }
오 좋습니다

2024-05-13 16:43 UTC, junseoplee commented on src/main/java/chess/view/InputView.java
> +  }
구현했습니다!

2024-05-13 16:54 UTC, junseoplee commented on src/main/java/chess/view/InputView.java
> +    }
1. 네!!
2. File과 Rank 클래스에 있습니다.

2024-05-14 11:13 UTC, junseoplee commented on src/test/java/chess/model/piece/pieces/KingTest.java
> +  }
물론 해당 클래스의 기능을 제대로 테스트할 수 있어야한다 생각합니다.
하지만 각 피스의 책임은 이동가능한 움직임을 갖게하는 것과 그 움직임에 따른 경로의 유효성을 판단하는 것이기 때문에 피스들의 테스트는 이것에 중점을 두었습니다.

2024-05-14 11:16 UTC, junseoplee commented on src/test/java/chess/model/piece/pieces/PawnTest.java
> +
체스 경험이 없어 죽을 뻔 했습니다. 특히 폰..

2024-05-14 11:21 UTC, junseoplee commented on src/test/java/chess/model/piece/pieces/PawnTest.java
> +    Pawn pawn = new Pawn(fromRank == 2 ? Color.WHITE : Color.BLACK);
좋아요!

2024-05-14 13:31 UTC, junseoplee commented on src/main/java/chess/model/board/Board.java
> +  }
동등성 검사를 추가하여 테스트를 추가했습니다!

2024-05-14 13:46 UTC, junseoplee commented on src/main/java/chess/model/piece/pieces/King.java
> +import chess.view.ErrorMessage;
맞습니다. 모델은 뷰에 대한 정보도 알지 못해야 합니다. DIP 위반이네요.
`ErrorMessage` enum은 model에 존재해야 할듯합니다.

2024-05-14 13:53 UTC, junseoplee commented on src/main/java/chess/model/piece/pieces/Pawn.java
> +    // Pawn의 경우 목적지에 도착했을 때 색 검사를 하지 않음
아직 규칙을 잘 모를 때 작성했나봅니다.

2024-05-19 10:14 UTC, poi1649 requested changes
깔끔하게 수정하시느라 고생 많으셨습니다.
진짜 마지막으로 아주 자잘한 커멘트 몇 개 남겼으니 확인부탁드려요!

2024-05-19 10:14 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +    if (receivedCommand.getCommand().equals(END_COMMAND)) {
객체를 만들었는데 getter를 꼭 사용해야할까요? 의식적으로 getter 사용을 지양하는 연습을 해보는 것도 좋습니다!

2024-05-19 10:14 UTC, poi1649 commented on src/test/java/chess/model/CommandTest.java
> +  }
정상테스트까지 꼼꼼하게 작성하는 것 좋네요👍 참고로 예외를 던지지 않는지만 볼 거면 assertDoesNotThrow 라는 메서드도 있어요!

2024-05-19 10:14 UTC, poi1649 commented on src/main/java/chess/model/piece/Piece.java
> +  }
color가 같으면 같은 piece로 인식해도 괜찮을까요?

2024-05-19 10:16 UTC, poi1649 commented on src/test/java/chess/model/piece/pieces/PawnTest.java
> +
ㅋㅋㅋ 우리때는 체스 안해본 사람 없었는데.. 세대 차이가 느껴지네요

2024-05-20 17:21 UTC, junseoplee commented on src/main/java/chess/model/piece/Piece.java
> +    }
null이 발생하는 경우는 보드 위 해당 위치에 피스가 없는 경우입니다.
하지만 이 경우에는 `Board`의 `validateNotEmpty` 메서드에서 체크되어 예외 처리됩니다. 따라서 null이 들어오는 경우는 없습니다.

2024-05-22 17:50 UTC, junseoplee commented on src/main/java/chess/controller/ChessController.java
> +    if (receivedCommand.getCommand().equals(END_COMMAND)) {
인터페이스를 활용하여 각 명령을 처리하는 클래스를 생성했습니다. 명시성, 확장성에 이점이 있습니다.
클래스는 각자의 실행 기능을 갖고있습니다.
명령어 입력에 따라 해당 클래스를 실행하여 원하는 기능을 작동하게 합니다.

2024-05-22 18:17 UTC, junseoplee commented on src/main/java/chess/model/piece/Piece.java
> +  }
객체의 color와 함께 객체의 유형을 비교하도록 변경했습니다.

2024-05-26 09:06 UTC, poi1649 approved these changes
이번 단계도 고생많으셨습니다. 추가적으로 몇개 커멘트 남겼는데 이 부분은 다음단계 진행하며 반영해주세요~

2024-05-26 09:06 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +        if (!(receivedCommand instanceof StartCommand) && !(receivedCommand instanceof EndCommand)) {
1. instanceof 의 사용은 캡슐화가 깨진 것이라고도 해석할 수 있어요!
[관련 글1](https://tecoble.techcourse.co.kr/post/2021-04-26-instanceof/), [관련 글2](https://ksh-coding.tistory.com/84)읽어보셔도 좋습니다~

2. 부정 조건문 사용에는 몇가지 단점이 있어요!
이 부분도 [관련 글](https://schneide.blog/2014/08/03/dont-ever-not-avoid-negative-logic/) 첨부합니다!

2024-05-26 09:06 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +  public void endGame() {
<img width="570" alt="스크린샷 2024-05-26 오후 5 57 04" src="https://github.com/poi1649/java-chess/assets/74969077/f35f1e09-1620-4f65-a8ce-2b5d370ed6d7">

2024-05-26 09:06 UTC, poi1649 commented on src/main/java/chess/model/command/CommandFactory.java
> +    });
람다 사용이 아주 적절하네요 👍 
퀴즈: 두번째 인자는 어떤 함수형 인터페이스일까요?

2024-05-26 09:06 UTC, poi1649 commented on src/main/java/chess/model/command/CommandFactory.java
> +    int rank = position.charAt(1) - '0';
이런식으로 int 로 관리해줘도 나쁠 건 없지만, String 형태로 A 라는 알파벳 자체로 저장하는 것도 고려해보는건 어떨까요?
개인적으로 웹 개발에서는 아주 약간의 성능과 가독성의 트레이드 오프에서  가독성을 조금 더 챙기는 방향을 가져가는 걸 선호하기는 합니다.

2024-05-26 09:06 UTC, poi1649 commented on src/main/java/chess/model/piece/Piece.java
> +      throw new IllegalArgumentException(ErrorMessage.INVALID_TURN.getMessage());
[이런 의견](https://madplay.github.io/post/effectivejava-chapter10-exceptions#%EC%95%84%EC%9D%B4%ED%85%9C-72-%ED%91%9C%EC%A4%80-%EC%98%88%EC%99%B8%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC) 도 있습니다!

2024-05-26 09:06 UTC, poi1649 commented on src/main/java/chess/model/piece/pieces/Bishop.java
> +    Movement movement = convertMovement(from, to);
static 메서드로 바꿔준 이유가 있나요?

2024-05-26 09:07 UTC, merged

2024-05-26 16:12 UTC, junseoplee commented on src/main/java/chess/controller/ChessController.java
> +        if (!(receivedCommand instanceof StartCommand) && !(receivedCommand instanceof EndCommand)) {
와오 감사합니다

2024-05-26 16:12 UTC, junseoplee commented on src/main/java/chess/controller/ChessController.java
> +  public void endGame() {
ㅋㅋㅋㅋ

2024-05-27 06:53 UTC, junseoplee commented on src/main/java/chess/model/command/CommandFactory.java
> +    });
`Map<String, Function<List<String>, CommandLauncher>>` 에서 두 번째 인자인 Function 함수형 인터페이스인가요?
List<String> 타입의 입력을 받아서(parts) apply를 통해  CommandLauncher 타입의 출력을 리턴하는 인터페이스입니다
commandMap에 명령어 문자열을 키로 하고 CommandLauncher 객체를 반환하는 함수를 값으로 저장해요

2024-05-27 07:28 UTC, junseoplee commented on src/main/java/chess/model/command/CommandFactory.java
> +    int rank = position.charAt(1) - '0';
File enum을 char로 열거하면 가능합니다. 하지만 차이를 계산하기 위해서는 int로 변환을 해야하며, a를 1로 매핑하는 식으로 file에서 작업을 한 번 더 거쳐야하네요
물론 char 자체는 정수로 저장되기 때문에 계산이 가능하지만...
Movement로 변환하기 위해서는 너무 많은 로직을 변경해야해요ㅜㅜ
다음부터는 가독성을 더 챙기는 방향으로 결정해보겠습니다

2024-05-27 07:28 UTC, junseoplee commented on src/main/java/chess/model/piece/Piece.java
> +      throw new IllegalArgumentException(ErrorMessage.INVALID_TURN.getMessage());
오오 저번에 말씀해주셨던 내용이네요 감사합니다!!

2024-05-27 07:36 UTC, junseoplee commented on src/main/java/chess/model/piece/pieces/Bishop.java
> +    Movement movement = convertMovement(from, to);
이쪽이 가독성이 좋다 판단했습니다!
하지만 객체지향과 멀어진다는 느낌이 있을 수도 있습니다. 메모리 성능 측면에서 손해가 있을 수도 있구요.
그래도 to와 from의 Position 클래스에 책임이 있는 메서드가 아니라 MovementConverter 클래스에 책임이 있기 때문에 to 객체 자체의 행위가 아니라 정적 메서드로 변경해도 좋다 생각했습니다.
(e.g. `to.calculateFileDiff(from);` 는 책임이 Position 클래스 안에 있음)