[2단계 체스미션] 이유빈 미션 제출합니다.
poi1649/java-chess pull request #5
Opened 2024-05-08 22:09 UTC by leeshin20

2024-05-12 11:17 UTC, poi1649 requested changes

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/ui/OutputView.java
> +        System.out.println("> 게임 이동 : move source위치 target위치 - 예. move b2 b3");
`fix: 초기 출력 메시지 변경` 
출력 메시지 변경은 fix 인가요?  fix는 [컨벤션](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message) 상 언제 사용해야할까요?

2024-05-12 11:17 UTC, poi1649 commented on src/test/java/chess/BoardTest.java
> +        assertNull(testBoard.findPiece(target));
findPiece를 했을 때 기물이 없으면 null 을 반환하네요
null을 반환할 때 생기는 문제는 뭐가 있을까요?
null을 반환하는 대신 기물이 없다는 것을 나타낼 수 있는 방법은 없을까요?

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/position/Position.java
> +        }
사용자가 잘못 입력한 것이 file인지 rank 인지 정확히 알 수는 없겠네요.
가끔 어떤 프로그램이나 사이트를 이용할 때 에러 메시지가 불친절해서 스트레스 받았던 기억이 있지 않으신가요?

2024-05-12 11:17 UTC, poi1649 commented on README.md
> +```
꾸준한 문서 업데이트 좋습니다👍👍

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/piece/Piece.java
> +    public Piece(final Team team) {
ㅋㅋㅋ Type 으로 설정하기엔 한계가 있었나요?

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/ui/ExtractPieceSymbol.java
> +        symbolMap.put(King.class, "K");
static 블록을 사용하셨군요 static 블록이 무엇이고 사용하면 어떤 이점이 있나요?

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/ui/ExtractPieceSymbol.java
>  public class ExtractPieceSymbol {
class 이름은 명사로 작성합니다

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/position/File.java
> +    }
꼭 static 메서드로 만들 필요는 없어보이는데, static으로 만드신 이유가 있나요?

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +                if (proceedGame(board).equals(END_COMMAND)) {
메서드 이름만 봤을 때 proceedGame 메서드가 커멘드를 반환하는게 자연스럽게 느껴지지는 않네요

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +        Position target = searchPosition(locations.get(1));
0, 1 이라는 숫자는 무슨 의미인가요?

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +    }
핵심적인 기능같은데 테스트는 어디갔을까요

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/piece/Piece.java
> +        return 0;
1, -1 , 0 은 무슨뜻인가요?
메서드 이름에서 방향을 나타낸다는 건 알겠는데, 각각의 숫자가 어떤 방향을 나타내는지 알기가 쉽지 않네요. 원시값이 아닌 다른 형태로 관리해주는건 어떨까요

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/piece/Piece.java
> +    }
Piece라는 상위 클래스가 하위 클래스의 정보를 가지고 있네요. 의존성 역전 원칙, 리스코프 치환 원칙에 위배될 것 같아요. 각각의 원칙들에 위배되면 어떤 문제가 생길까요?

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/board/Board.java
> +        if (selectedPiece instanceof Pawn) {
instanceof 키워드를 사용하게 될 때는 과연 설계가 올바른지를 한 번 더 생각해볼 필요가 있습니다.
[관련 글](https://ksh-coding.tistory.com/84#:~:text=instanceof%20%EC%97%B0%EC%82%B0%EC%9E%90%EB%8A%94%20%EA%B0%9D%EC%B2%B4%EA%B0%80,boolean%20%EB%B0%98%ED%99%98%ED%83%80%EC%9E%85%EC%9D%84%20%EA%B0%80%EC%A7%84%EB%8B%A4.) 읽어보시는 걸 추천드려요

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/move/Movement.java
> +    }
position이 int(원시값) 대신 Rank, File 을 가졌을때(원시값 포장을 했을 때) 어떤 이점이 있을까요?

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/piece/Bishop.java
> +        verifyMovement(MOVABLE_DIRECTION, movement);
모든 기물에서 verifyMovement를 명시적으로 호출해주어야하네요. 시스템적으로 이 메서드 사용을 강제하는 장치도 없고, 메서드 자체도 Piece 객체에 숨겨져 있어서 다른 객체를 만들다가 실수할 확률이 높아보입니다. 이를 어떻게 해결할 수 있을까요?

2024-05-12 11:17 UTC, poi1649 commented on src/main/java/chess/piece/Pawn.java
> +        return movements;
이런 복잡한 기능에도 테스트가 없어도 될까요? 
사실 이 기능을 제외해도 전체적으로 테스트가 많이 부족합니다... 🥲

2024-05-16 14:58 UTC, leeshin20 commented on src/main/java/chess/piece/Piece.java
> +    public Piece(final Team team) {
1단계 미션을 진행할 때는 각 기물 별 이동 기능이나 규칙 등을 크게 고려하지 않고 Piece 클래스를 구현했습니다.

그런데 체스 말의 이동 기능을 구현하려고 하니까 기물들을 각각 다른 이동 규칙과 제약조건을 가지고 있었고
이것들을 Piece 클래스를 상속받는 별개의 클래스로 구현하도록 수정했습니다!

따라서 `Knight``Pawn``King`과 같이 클래스의 타입으로 기물의 종류를 구분할 수 있게 되었기 Type클래스는 삭제해주었습니다.

2024-05-16 15:05 UTC, leeshin20 commented on src/main/java/chess/ui/ExtractPieceSymbol.java
>  public class ExtractPieceSymbol {
메서드는 동사
클래스는 명사
기억하겠습니다!

2024-05-16 15:49 UTC, leeshin20 commented on src/main/java/chess/position/File.java
> +    }
```
    public void verifyPath(Position start, Position target) {
       <변경 전>
        int fileGap = Position.fileGap(start, target);
        int rankGap = Position.rankGap(start, target);
       <변경 후>
        int fileGap = start.fileGap(target);
        int rankGap = start.rankGap(target);
```

static이 없어도 구현할 수 있는 메서드였는데 `fileGap(start, target)` 파라미터로 시작, 목표를 둘 다 받는 형태에 집착을 하다 보니까 그렇게 된 것 같습니다.
이 상태에서 static으로 구현하지 않게 되면 `start.fileGap(start, target)` start가 두 번 들어가서 static으로 구현하면 좀 깔끔하게 보일 것 같은데... 하는 바보같은 생각을 해서 그렇게 되었습니다.

2024-05-16 16:13 UTC, leeshin20 commented on src/main/java/chess/ChessGameManager.java
> +                if (proceedGame(board).equals(END_COMMAND)) {
다시 보니 while문도 사용할 필요가 없었는데 뇌가 굳어서 이상한 코드를 작성한 것 같습니다.

커맨드를 반환하지 않도록 수정했습니다!

2024-05-16 17:41 UTC, leeshin20 commented on src/main/java/chess/ChessGameManager.java
> +        Position target = searchPosition(locations.get(1));
해당 부분만 보면 제가 봐도 의미가 모호하다고 느껴집니다!

0, 1 이라는 숫자를 상수로 관리하도록 수정하고, 해당 부분을 조금 더 이해하기 쉽게 하고자 
`extrectStartPosition` `extractTargetPosition` 라는 메서드로 분리해보았습니다

2024-05-16 17:51 UTC, leeshin20 commented on src/main/java/chess/ui/OutputView.java
> +        System.out.println("> 게임 이동 : move source위치 target위치 - 예. move b2 b3");
`fix`는 버그 수정의 경우 사용하는 것이 바람직하고,
해당 경우에는 `refactor`를 사용하는 것이 맞는 것 같습니다.

2024-05-16 17:54 UTC, leeshin20 commented on src/main/java/chess/position/Position.java
> +        }
조건을 하나의 if문으로 처리하는 것이 멋진 코드일거라 생각했는데 사용자의 입장을 생각하지 못 했습니다!

예외처리를 세분화하여 정확한 예외 메시지를 출력하도록 수정 했습니다!

2024-05-16 19:43 UTC, leeshin20 commented on src/main/java/chess/ui/ExtractPieceSymbol.java
> +        symbolMap.put(King.class, "K");
static 블록은 인스턴스와 무관하게 클래스가 로드될 때 한 번 실행되는 블록입니다.

`ExtreactPieceSymbol`와 같은 유틸리티 클래스는 인스턴스화 불가능하기 때문에 생성자를 통한 초기화가 불가능합니다.
그래서 위와 같이 HashMap을 초기화 하기 위해서 초기화 기능을 하는 메서드를 따로 만드는 등의 과정이 필요하지만 static 블록을 사용하면 이런 과정을 거치지 않고 초기화가 가능합니다.

2024-05-17 02:13 UTC, leeshin20 commented on src/main/java/chess/piece/Piece.java
> +        return 0;
Direction이라는 enum으로 관리하도록 수정했습니다.
file, rank 구분 없이 
`POSITIVE` : 현재 위치 기준, + 방향으로 이동할 때
`NEGETIVE` : 현재 위치 기준 - 방향으로 이동할 때
`STATIONARY` : 현재 위치 기준 움직임이 없을 때

2024-05-17 03:29 UTC, leeshin20 commented on src/main/java/chess/move/Movement.java
> +    }
```
    public Position nextPosition(File file, Rank rank) {
        return new Position(file.value() + this.file, rank.value() + this.rank);
    }
```
원시값을 포장하도록 수정했습니다!!

원시값을 포장하면 메서드가 어떤 기능을 하는지, 파라미터 값은 정확히 어떤 값을 의도하고 작성한건지 의미를 명확하게 하여 가독성을 올려줍니다.

객체로 포장하게 되면, 해당 값이 속하는 객체가 명확해지기 때문에 객체 스스로 상태를 관리할 수 있도록 코드를 짜는데 도움을 줍니다.

원시타입인 int로 file, rank 값을 받는다면, 값에 대한 검증이 이뤄지지 않았기 떄문에 체스판의 범위(1~8)을 넘어가는 값을 입력 받아도 정상적인 예외처리를 하지 못 하거나, 이를 검증하기 위해 추가적으로 검증 기능을 구현해야 됩니다.
하지만 File, Rank를 가지게 된다면 추가적인 코드 작성 없이도 각각 File 객체는 file 값에 대해, Rank 객체는 rank 값에 대해 유효성 체크를 하게 됩니다.

2024-05-17 03:34 UTC, leeshin20 commented on src/main/java/chess/piece/Bishop.java
> +        verifyMovement(MOVABLE_DIRECTION, movement);
```
<수정 전>
// 이동 방향을 찾는 메서드
Movement movement = Movement.findMovementByDirection(this, MOVABLE_DIRECTION, start, target);
// 앞에서 찾은 이동 방향을 검증하는 메서드
verifyMovement(MOVABLE_DIRECTION, movement);
```
위 처럼 이동 방향을 찾는 메서드를 호출한 뒤, 검증 메서드를 따로 호출해줘야 했지만, 
이동 방향을 찾는 메서드 `Movement.findMovement` `Movement.findMovementByDirection` 안에서 검증하는 메서드까지 함께 수행하도록 수정해보았습니다!

2024-05-17 03:51 UTC, leeshin20 commented on src/main/java/chess/board/Board.java
> +        if (selectedPiece instanceof Pawn) {
```
        if (selectedPiece.isPawn()) {
            selectedPiece.checkTargetPositionByPawn(targetPiece, start.fileGap(target));
        }
```
수정했습니다!!

instanceof를 사용하면 간결하고 쉽게 구현이 된다고 생각했는데, 원칙에 위배되는 부분들은 생각하지 못 했습니다
꼭 필요한 경우가 아니라면 instanceof 사용은 지양하도록 하겠습니다!

2024-05-17 04:29 UTC, leeshin20 commented on src/test/java/chess/BoardTest.java
> +        assertNull(testBoard.findPiece(target));
null은 해당 포지션에 기물이 없을 경우를 상정하고 null을 반환하도록 코드를 작성하였지만, 미리 상정해둔 상황 외에도 NullPointerException이 발생할 가능성이 있고, null 자체가 명확하지 않은 의미를 가지기 때문에 이런 경우 정확한 원인을 찾는데 어려움이 있을 수 있습니다.

그래서 빈칸을 null로 처리하는 것이 아니라, EmptyPiece라는 객체를 만들어서 빈 칸에도 EmptyPiece라는 Piece가 존재하도록 수정했습니다. 

기존에 `targetPiece == null `와 같이 칸이 비어있는지 확인하던 코드도
`targetPiece.isEmpty()` 이와 같이 수정하였습니다.

2024-05-17 11:39 UTC, leeshin20 commented on src/main/java/chess/piece/Piece.java
> +    }
의존성 역전 원칙을 위배하게 되면, 추상화를 통해 기능의 추가, 확장 등을 용이하게 하는 유연성을 해치고, 변경이 생길 때 마다 많은 부분의 코드를 수정해야 될 수 있기 때문에 유지보수에 어려움을 줍니다. 하위 클래스에 직접 접근하게 된다면 상위 클래스 기능의 재사용성에 문제가 생길 수 있습니다.

리스코프 치환 원칙을 위배하게 된다면, Piece를 상속 받은 객체들은, 부모 객체인 Piece의 기능을 완전하게 대체할 수 있어야 되는데 해당 코드에서는 Piece 클래스에서 Pawn과 관련된 메서드가 등장하며, Pawn의 정보에 접근할 수 없는 Knight, Bishop과 같은 객체의 경우 리스코프 치환 원칙에서 위배됩니다. 이 경우 상속 구조의 일관성을 해치게 되고 유지보수를 어렵게 만들고, 부모 객체와 자식 객체가 다른 동작을 수행하는 등의 문제가 발생할 수 있습니다.

`piece.checkTargetPosition` 다형성을 이용하여 Piece객체에서 Pawn에 대한 정보를 가지지 않도록 코드를 수정했습니다!

2024-05-17 15:48 UTC, leeshin20 commented on src/main/java/chess/ChessGameManager.java
> +    }
현재 턴을 검증하는 테스트 코드를 추가했습니다!

2024-05-17 15:51 UTC, leeshin20 commented on src/main/java/chess/piece/Pawn.java
> +        return movements;
폰의 전체적인 경로 탐색 메서드의 테스트는 가능한데, 해당 메서드 하나의 단위 테스트를 작성을 어떻게 해야될지 감이 안 잡혔습니다.
애초에 클래스나 메서드 구조를 잘못 설계한게 아닌가 생각이 됩니다.

계속해서 개선해 보도록 하겠습니다.

2024-05-19 10:29 UTC, poi1649 commented on src/test/java/chess/BoardTest.java
> +        assertNull(testBoard.findPiece(target));
훌륭합니다.

2024-05-19 10:31 UTC, poi1649 commented on src/main/java/chess/position/Position.java
> +        }
좋습니다. 사실 백엔드 프로그래밍을 하다보면 사용자가 프론트엔드 개발자인 경우가 많아서, 이 부분이 더 와닿지 않더라고요. 지금부터라도 미리미리 상세한 예외처리를 습관화 해놓는 게 좋습니다.

2024-05-19 10:31 UTC, poi1649 commented on src/main/java/chess/piece/Piece.java
> +    public Piece(final Team team) {
사실 프로그램을 짜다보면 내가 도메인을 완전히 이해하지 않고 프로그램을 짜게 되는 경우가 많죠ㅋㅋㅋ 이런 경우 어떻게 해야 미래의 내가 덜 고생할지 고민해보셔도 좋아보입니다.

2024-05-19 10:33 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +                if (proceedGame(board).equals(END_COMMAND)) {
ㅋㅋㅋㅋ 뇌가 자주 굳네요. 공부좀 그만하고 나가서 애니도 보고 그러세요

2024-05-19 10:33 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +        Position target = searchPosition(locations.get(1));
훌륭합니다. 🥲

2024-05-19 10:34 UTC, poi1649 commented on src/main/java/chess/piece/Piece.java
> +        return 0;
좋습니다. 👍👍 이럴 때 Enum으로 관리하면 의미도 명확해지고 책임 넘겨주기도 좋죠

2024-05-19 14:19 UTC, poi1649 requested changes
테스트 정말 꼼꼼하네요. 고생 많으셨습니다.
소소한 커멘트 남겼으니 확인 부탁드려요

2024-05-19 14:19 UTC, poi1649 commented on src/main/java/chess/piece/Pawn.java
> +        if (this.getTeam().equals(Team.WHITE)) {
getter 대신 메서드를 만들어주는 건 어떨까요?

2024-05-19 14:19 UTC, poi1649 commented on src/main/java/chess/move/Movement.java
> +import chess.piece.Piece;
piece와 movement가 양방향의존을 가지고 있네요. 어떤 문제가 발생할 수 있을까요?

2024-05-19 14:19 UTC, poi1649 commented on src/main/java/chess/position/Position.java
> +    }
enum을 만들어놓고 정작 원시값을 반환해서 enum의 장점이 조금 퇴색되는 것 같네요

2024-05-19 14:19 UTC, poi1649 commented on src/test/java/chess/piece/PawnTest.java
> +public class PawnTest {
마음이 편안해지네요 꼼꼼한 테스트 굳입니다. 
사실 폰 코드를 보고 이 동작도 지원할까? 싶은 의문이 있었는데 테스트 코드에 해당 예시가 있어서 안심하게 됐어요 👍

2024-05-19 14:19 UTC, poi1649 commented on src/main/java/chess/position/Position.java
> +            return this.rank.value() == BLACK_PAWN_INITIAL_RANK;
이런 부분도 enum을 직접 비교하는게 원시값을 비교하는 것보다 이점이 있어보이네요.

2024-05-19 14:19 UTC, poi1649 commented on src/main/java/chess/move/Movement.java
> +                .filter(move -> move.file == file && move.rank == rank)
movement, direction, position은 각각 어떤 책임을 갖는 것을 목표로 설계된 클래스일까요?

2024-05-19 14:21 UTC, poi1649 commented on src/main/java/chess/position/File.java
> +    }
ㅋㅋㅋ 좋습니다. 사실 static, instance 둘 중 어느 것이 명확하게 좋다 라는 건 없고, 각각 장단점이 있어요.
각각의 장단점을 이 기회에 한 번 찾아보시죠

2024-05-19 14:22 UTC, poi1649 commented on src/main/java/chess/piece/Piece.java
> +    }
좋습니다. 상속을 왜 사용하는지, 어떨 때 이점이 있는지 와닿게 되는 계기가 됐으면 좋겠네요.
추가로 `상속보다 조합` 이라는 키워드에 대해서도 공부해보셔도 좋아요

2024-05-19 14:28 UTC, poi1649 commented on src/main/java/chess/piece/Piece.java
> +    public void verifyMovement(List<Movement> movableDirections, Movement movement) {
piece 안에 있을 필요가 있을까요?

2024-05-23 12:54 UTC, leeshin20 commented on src/main/java/chess/piece/Piece.java
> +    public void verifyMovement(List<Movement> movableDirections, Movement movement) {
전혀 없는 것 같습니다...

`Movement`클래스로 이동했습니다!

2024-05-23 13:49 UTC, leeshin20 commented on src/main/java/chess/position/Position.java
> +            return this.rank.value() == BLACK_PAWN_INITIAL_RANK;
```
    public boolean onInitialRankWhitePawn() {
        return this.rank == Rank.findByValue(WHITE_PAWN_INITIAL_RANK);
    }

    public boolean onInitialRankBlackPawn() {
        return this.rank == Rank.findByValue(BLACK_PAWN_INITIAL_RANK);
    }
```

원시값 value가 아닌 enum을 직접 비교하도록 수정했습니다!

2024-05-23 14:56 UTC, leeshin20 commented on src/main/java/chess/move/Movement.java
> +                .filter(move -> move.file == file && move.rank == rank)
`position`은 체스판 위의 file, rank 값을 가지는 좌표에 대한 책임을 갖습니다.

`movement`는 `piece`가 가질 수 있는 이동 규칙에 대한 책임을 갖습니다.

`direction`은 (`bishop` `queen` `rook`)의 두 칸 이상 이동한 거리에서 방향만을 추출한 값(1, -1, 0) 값에 대한 책임을 갖습니다.

위 처럼 설계를 했는데, `direction`의 경우 `movement`가 가지는 이동 규칙과 책임이 겹치는 부분이 있다고 생각이 되어 삭제 후 `movement`에서 관리하도록 수정했습니다.

2024-05-23 15:04 UTC, leeshin20 commented on src/main/java/chess/move/Movement.java
> +import chess.piece.Piece;
`piece`와 `movement`가 양방향 의존성을 가지고 있다면, 구조 상 하나의 클래스가 해야될 역할을 억지로 나눠놓았다고 해석될 수 있으며, 두 클래스의 결합성이 올라가서 기능을 변경하거나 새로 추가할 때, 이를 수정하는 과정이 복잡해집니다. 더불어 단위 테스트나 코드를 재사용 하는 것도 어려움이 생깁니다.

2024-05-23 15:06 UTC, leeshin20 commented on src/main/java/chess/piece/Pawn.java
> +        if (this.getTeam().equals(Team.WHITE)) {
`getTeam` 대신 `checkSameTeam` 메서드를 만들어, Team의 값을 반환하는 것이 아니라, 메서드에서 팀을 비교하고 boolean 타입을 반환하도록 수정 했습니다.

2024-05-23 15:25 UTC, leeshin20 commented on src/main/java/chess/position/Position.java
> +    }
Direction과 Movement의 역할이 일부 겹친다고 생각이 되어, Direction enum을 삭제하고 해당 값들을 상수로 대체하게 되었는데, 기존 방식대로 enum으로 관리하는 쪽이 더 좋은 방식인지 궁금합니다.

2024-05-26 08:46 UTC, poi1649 approved these changes
수정내용 확인했습니다 고생 많으셨고, 다음단계 가시죠!

2024-05-26 08:46 UTC, poi1649 commented on src/main/java/chess/piece/Pawn.java
> +        if (this.checkSameTeam(targetPiece.getTeam())) {
team을 꼭 get을 해야할까요? 다른 Piece를 받아서 아래와 같이 확인 할 수도 있을 것 같아요
getter 사용을 지양하는 연습을 습관적으로 해주세요~ 
```suggestion
        if (this.isSameTeam(targetPiece)) {
```

2024-05-26 08:50 UTC, poi1649 commented on src/main/java/chess/position/Position.java
> +    }
굳이 `열거형 상수`를 상수로 치환할 필요가 있을까요?

현재 구조를 유지하고, Movement 가 상수 대신 Direction enum을 사용하는 것도 괜찮아보여요

2024-05-26 08:50 UTC, poi1649 commented on src/main/java/chess/move/Movement.java
> +import chess.piece.Piece;
👍 추가로 toString 같은 메서드를 정의할 때 무한 반복이 생길 수도 있습니다.

2024-05-26 08:51 UTC, merged

2024-05-29 03:49 UTC, leeshin20 commented on src/main/java/chess/piece/Pawn.java
> +        if (this.checkSameTeam(targetPiece.getTeam())) {
getter를 삭제하고 해당 부분들은 `isSameTeam`으로 대체하도록 수정했습니다!