[3단계 - 승패 및 점수] 이유빈 미션 제출합니다
poi1649/java-chess pull request #8
Opened 2024-05-30 13:53 UTC by leeshin20

2024-06-02 09:29 UTC, poi1649 requested changes
요구사항에 있는 기능은 정확하게 구현해준 것 같네요👍👍 
기능 외적인 면에서 고민해볼만한 부분이 보여서 커멘트 몇 개 남겼습니다. 확인 부탁드려요~

2024-06-02 09:29 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +        if(board.findPiece(target).isKing()) {
if 다음 공백이 없네요 `cmd + opt + l` 눌러주세요!

2024-06-02 09:29 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +            System.exit(0);
System.exit 말고 다른 종료 방법은 없을까요?

2024-06-02 09:29 UTC, poi1649 commented on src/main/java/chess/piece/Score.java
> +}
불필요한 두 줄 공백이 두개나 있네요. 컨벤션을 잘 지키는 것도 중요합니다!

2024-06-02 09:29 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +// move h5 e8
??? 이거 계속 입력하지 말고 테스트코드를 짜는건 어떨까요?

2024-06-02 09:29 UTC, poi1649 commented on src/main/java/chess/ChessGameManager.java
> +            board.movePiece(start, target);
movePiece에서 예외가 발생해도 킹 사망 문구가 출력될 수 있겠네요

2024-06-02 09:29 UTC, poi1649 commented on src/test/java/chess/ui/OutputTest.java
> +}
1. 테스트코드에 킹이 죽었다는 흔적은 없는데 킹이 죽은 경우를 테스트한다는 메서드명이 적절할까요?
2. 이 코드는 무엇을 테스트하는 코드일까요?
3. 테스트코드는 언제 필요할까요?

2024-06-02 09:29 UTC, poi1649 commented on src/main/java/chess/piece/Score.java
각 피스 클래스안에 score 필드를 넣는 것과 enum안에서 피스 클래스들을 관리하는것 각각 어떤 장단점이 있을까요?

2024-06-02 09:29 UTC, poi1649 commented on src/main/java/chess/piece/Score.java
> +        int pawnCount = 0;
모든 메서드가 public으로 열려있는 이유가 있나요?

2024-06-02 09:29 UTC, poi1649 commented on src/main/java/chess/piece/Score.java
> +        }
stream을 사용하기에 딱 좋은 예시네요! stream 을 사용해서 수정해볼까요?

2024-06-02 09:29 UTC, poi1649 commented on src/test/java/chess/piece/ScoreTest.java
> +public class ScoreTest {
꼼꼼한 테스트코드 훌륭합니다 💯💯

그런데 밑의 요구사항을 지키지는 않은 것 같네요. 🥲

```모든 기능을 TDD로 구현해 단위 테스트가 존재해야 한다. 단, UI(System.out, System.in) 로직은 제외```

2024-06-02 09:29 UTC, poi1649 commented on src/test/java/chess/piece/ScoreTest.java
> +        assertThat(Score.findScoreByPiece(new Rook(Team.BLACK))).isEqualTo(Score.ROOK_SCORE);
여러개의 메서드를 검증할 때, assertAll, softAssertions 같은 메서드를 사용해볼 수 있습니다. 
assertThat 여러개를 사용할때와 어떤 차이가 있을까요?

2024-06-07 10:18 UTC, leeshin20 commented on src/test/java/chess/piece/ScoreTest.java
> +        assertThat(Score.findScoreByPiece(new Rook(Team.BLACK))).isEqualTo(Score.ROOK_SCORE);
assertThat 여러개를 사용하면 순서대로 어설션을 실행할 때, 하나라도 실패하게 되면 실행이 종료되며 그 뒤에 있는 어설션의 결과를 확인할 수 없게 됩니다

assertAll과 softAssertions를 사용하게 되면 중간에 실패하게 되더라도 즉시 테스트가 종료되는 것이 아니라, 나머지 어설션까지 모두 실행한 후에 결과를 보여주기 때문에 전체 결과를 한 번에 볼 수 있습니다.

2024-06-07 10:28 UTC, leeshin20 commented on src/main/java/chess/piece/Score.java
> +        int pawnCount = 0;
public, private 어느 쪽으로 선언할지 바로 판단이 되지 않아서 일단 public으로 만든 후, 사용 여부를 보고 수정하려고 했는데 깜빡 잊은 것 같습니다. 컨벤션도 그렇고 꼼꼼히 확인하도록 하겠습니다.

2024-06-07 10:34 UTC, leeshin20 commented on src/main/java/chess/ChessGameManager.java
> +        if(board.findPiece(target).isKing()) {
저장하면서 항상 한번씩 눌러주겠습니다

2024-06-07 10:35 UTC, leeshin20 commented on src/main/java/chess/ChessGameManager.java
> +// move h5 e8
테스트코드에 더 익숙해지도록 하겠습니다...

2024-06-07 10:38 UTC, leeshin20 commented on src/main/java/chess/ChessGameManager.java
> +            board.movePiece(start, target);
잘못 적었는데 커밋할 때 제대로 확인을 못 하고 올린 것 같습니다!

커밋도 좀 더 꼼꼼하게 하도록 하겠습니다

2024-06-07 10:41 UTC, leeshin20 commented on src/main/java/chess/piece/Score.java
> +}
사소한 컨벤션이라고 생각했는데, 최근에 팀 프로젝트를 하다 보니까 이런 사소한 컨벤션도 지키는 것이 중요하다는걸 몸소 느낍니다.
신경쓰도록 하겠습니다!

2024-06-07 11:05 UTC, leeshin20 commented on src/main/java/chess/ChessGameManager.java
> +            System.exit(0);
System.exit 대신 return으로 종료되도록 수정했습니다!

2024-06-07 11:30 UTC, leeshin20 commented on src/test/java/chess/ui/OutputTest.java
> +}
1. 말씀하신대로 킹이 죽는 것과 관련된 코드가 보이지 않고, 킹이 죽고 난 후에 메세지가 잘 출력되는지를 확인하는 기능만 하고 있기 때문에 적절하지 않아보입니다. `printWitchTeamWin` 같은 이름이 적절하지 않았을까 싶습니다.

2. endGame이라는 게임 종료를 알리는 메서드가 호출 되었을 때, 그 당시 상황에 따라 게임 종료 메시지가 올바르게 출력이 되는지 테스트 하고 있습니다.

3. 해당 기능이 잘 작동하는지 확인할 때 필요하고 주로 핵심기능이거나, 복잡한 로직을 가지고 있는 기능을 확인할 때 테스트코드를 작성하면 좋다고 생각합니다.

2024-06-07 12:28 UTC, leeshin20 commented on src/main/java/chess/piece/Score.java
score 필드
piece의 응집성이 높아집니다.
piece의 점수에 변동이 있을 경우, 모든 piece 클래스의 값을 찾아가며 변경해줘야 할 수 있습니다.

enum
점수에 변동이 있어도 enum 파일에서만 수정이 이뤄지기 때문에 관리가 쉽습니다.
해당 값이 어떤 의미를 갖는 값인지 명시 하기 떄문에 가독성이 높아집니다.

2024-07-19 06:02 UTC, merged