[3단계 - 승패 및 점수] 이준섭 미션 제출합니다.
poi1649/java-chess pull request #9
Opened 2024-05-31 09:22 UTC by junseoplee

2024-06-02 09:45 UTC, poi1649 requested changes
복잡한 요구사항 잘 구현해주셨네요👍 쉽지 않았을텐데 고생많으셨습니다~
기능 외적으로 몇가지 이야기해 볼 부분이 있어 커멘트 남겼으니 확인해주세요!

2024-06-02 09:45 UTC, poi1649 commented on src/main/java/chess/model/board/Board.java
> +  }
move 메서드에서 에서 원래 있던 기물이 삭제될 것 같은데, 굳이 먼저 삭제해준 이유가 있나요?

2024-06-02 09:45 UTC, poi1649 commented on src/main/java/chess/controller/ChessController.java
> +    }
piece type을 전체 다 확인할 필요가 있을까요? King 인지 확인하는 메서드정도로 충분해보이긴 하네요.
지금처럼 getter 를 사용해서 캡슐화를 깨고 Piece 객체 외부에 정보를 굳이 노출할 필요는 없어보여요🤔

2024-06-02 09:45 UTC, poi1649 commented on src/main/java/chess/model/score/ScoreCalculator.java
> +                                          .collect(Collectors.groupingBy(entry -> entry.getKey().getFile().getValue(), Collectors.counting()));
groupingBy 사용이 매우 적절하네요 👍👍

2024-06-02 09:45 UTC, poi1649 commented on src/main/java/chess/model/score/ScoreCalculator.java
> +  public static double calculate(Map<Position, Piece> board, Color color) {
static 메서드만을 사용하는 util 클래스의 장단점은 뭘까요?

2024-06-02 09:45 UTC, poi1649 commented on src/test/java/chess/model/score/ScoreCalculatorTest.java
> +  }
이 로직만 보고 다른 사람들이 빠르게 점수계산 로직을 파악하기는 쉽지 않을 것 같네요.
테스트 코드는 동료가 로직을 더 빠르게 파악할 수 있게하는 문서의 역할도 합니다 🙂

2024-06-02 09:45 UTC, poi1649 commented on src/main/java/chess/model/score/ScoreCalculator.java
> +    }
이 부분은 stream을 안쓰고 for문으로 처리해준 이유가 있나요?(그냥 궁금함)

2024-06-02 09:45 UTC, poi1649 commented on src/main/java/chess/model/movement/Path.java
>        throw new IllegalArgumentException(ErrorMessage.HAS_OBSTACLE.getMessage());
Path에 target까지 들어있는게 어색한 것 아닐까요!?

2024-06-03 04:55 UTC, junseoplee commented on src/main/java/chess/model/score/ScoreCalculator.java
> +    }
좀 더 직관적으로 보이고 간단해서요!

2024-06-03 04:59 UTC, junseoplee commented on src/main/java/chess/model/board/Board.java
> +  }
어라 커멘트 남겨주신 코드는 예전 코드 같아요 
```
private Piece capturePiece(final Position to) {
    return board.remove(to);
  }
private void movePiece(final Position from, final Position to) {
    Piece piece = board.remove(from);
    board.put(to, piece);
  }
```
잡힌 피스를 리턴하고 싶어서 먼저 삭제했습니다

2024-06-03 05:19 UTC, junseoplee commented on src/main/java/chess/controller/ChessController.java
> +    }
`pieceType()`메서드를 점수 계산을 위해 만들었는데 King인지 확인하는 용도로도 쓸 수 있으니 그대로 사용했습니다.
```
 @Override
 public PieceInfo pieceType() {
   return PieceInfo.KING;
 } 
```
객체 정보가 아닌 `PieceInfo` 열거형에서  해당 피스에 해당하는 점수와 타입을 확인하여 보여준다는 느낌으로 사용해서 캡슐화를 깬다고 생각 못했네요.

이런 메서드도 위배되는 방식일까요?

2024-06-03 05:20 UTC, junseoplee commented on src/main/java/chess/model/score/ScoreCalculator.java
> +                                          .collect(Collectors.groupingBy(entry -> entry.getKey().getFile().getValue(), Collectors.counting()));
SQL 배우면서 봤던 내용이 있어 재밌었어요

2024-06-03 05:26 UTC, junseoplee commented on src/main/java/chess/model/score/ScoreCalculator.java
> +  public static double calculate(Map<Position, Piece> board, Color color) {
Input을 넣으면 Output을 반환하는 식으로 해당 클래스의 기능이 명확하게 보여서 좋다 생각합니다.
인스턴스 생성 없이 바로 접근이 가능해서 편리하기도 합니다. 시간적인 측면에서 이점도 있겠네요.
한편으로는 메모리를 차지하기 때문에 무분별하게 사용하면 성능적인 단점도 있으리라 생각합니다.

2024-06-03 07:33 UTC, junseoplee commented on src/main/java/chess/model/board/Board.java
> +  }
Map에서 put 했을 때 리턴 값이 명시적으로 보이지 않는다 생각했습니다.

2024-06-03 07:34 UTC, junseoplee commented on src/main/java/chess/model/movement/Path.java
>        throw new IllegalArgumentException(ErrorMessage.HAS_OBSTACLE.getMessage());
어색합니다. 추가로 Board를 좀 더 깔끔하게 만들었습니다.

2024-06-03 07:41 UTC, junseoplee commented on src/test/java/chess/model/score/ScoreCalculatorTest.java
> +  }
테스트 코드가 문서의 역할도 하는 군요!

2024-07-19 06:01 UTC, merged